POST http://localhost:7156/events
content-type: application/json

{
    "name": "Conference",
    "description": "Annual tech conference",
    "location": "San Francisco",
    "date_time": "2024-08-18T10:00:00Z"
}

