POST http://localhost:7156/events
content-type: application/json

{
    "name": "Music Festival",
    "description": "A weekend-long music festival featuring various bands.",
    "location": "Austin, TX",
    "date_time": "2024-11-10T12:00:00Z"
}

